[2017-03-07 11:24:20,547] launcher  INFO    SCOOP 0.7 1.1 on darwin using Python 2.7.12 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:43:17) [GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)], API: 1013
[2017-03-07 11:24:20,547] launcher  INFO    Deploying 4 worker(s) over 1 host(s).
[2017-03-07 11:24:20,547] launcher  INFO    Worker distribution: 
[2017-03-07 11:24:20,548] launcher  INFO       127.0.0.1:	3 + origin
/Users/emilyschlafly/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/Users/emilyschlafly/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/Users/emilyschlafly/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/Users/emilyschlafly/anaconda/envs/py27/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
epileptor_util.py:290: RuntimeWarning: overflow encountered in double_scalars
  return (x1**3 - 3 * x1**2) * (x1 < 0) + \
epileptor_util.py:290: RuntimeWarning: invalid value encountered in multiply
  return (x1**3 - 3 * x1**2) * (x1 < 0) + \
epileptor_util.py:262: RuntimeWarning: overflow encountered in double_scalars
  x2_dot = -y2 + x2 - x2**3 + self.Irest2 + 2. * g - 0.3 * (z - 3.5)
epileptor_util.py:262: RuntimeWarning: invalid value encountered in double_scalars
  x2_dot = -y2 + x2 - x2**3 + self.Irest2 + 2. * g - 0.3 * (z - 3.5)
epileptor_util.py:294: RuntimeWarning: invalid value encountered in multiply
  return 0. * (x2 < -0.25) + (6 * (x2 + 0.25)) * (x2 >= -0.25)
epileptor_util.py:291: RuntimeWarning: overflow encountered in double_scalars
  (x1 * (x2 - 0.6 * (z - 4)**2)) * (x1 >= 0)
[2017-03-07 11:24:29,577] launcher  (127.0.0.1:58865) INFO    Root process is done.
[2017-03-07 11:24:29,578] launcher  (127.0.0.1:58865) INFO    Finished cleaning spawned subprocesses.
